name = "ProtectedArrays"
uuid = "cc189d76-b79b-4429-8ac4-62283b8a79d2"
authors = ["Federico Stra <stra.federico@gmail.com> and contributors"]
desc = "Array wrapper to prevent modifications"
license = "MIT"
version = "0.0.0"

[compat]
julia = "1.4"
